<?xml version="1.0" standalone="yes"?>
<!--
Snap Websites Server == taxonomy database setup (i.e. type tree)
Copyright (C) 2011-2012  Made to Order Software Corp.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
-->
<!DOCTYPE snap-tree [
<!ELEMENT snap-tree (content)*>
<!ELEMENT content (param|link)*>
<!ATTLIST content path CDATA #REQUIRED>
<!ELEMENT param (#PCDATA)>
<!ATTLIST param name CDATA #REQUIRED
                overwrite (yes|no) "no"
                force-namespace (yes|no) "yes">
<!ELEMENT link (#PCDATA)>
<!ATTLIST link name CDATA #REQUIRED
               to CDATA #REQUIRED
               mode CDATA "1:1">
]>
<snap-tree>
  <content path="/types">
    <param name="taxonomy::name">system_types</param>
    <param name="content::title">System Types</param>
    <param name="content::body">
      <![CDATA[<p>This page represents the root of your entire website taxonomy tree.</p>]]>
    </param>
  </content>
  <content path="/types/taxonomy">
    <param name="taxonomy::name">taxonomy</param>
    <param name="content::title">Taxonomy</param>
    <param name="content::body">
      <![CDATA[<p>This is the top of the taxonomy tree used to tag / categories your pages.</p>]]>
    </param>
  </content>
  <content path="/types/taxonomy/system">
    <param name="taxonomy::name">system_taxonomy</param>
    <param name="content::title">System Taxonomy</param>
    <param name="content::body">
      <![CDATA[<p>Pages to be linked to a plugin for a specific purpose as defined by the plugin are linked using an entry under this path. For example the robots.txt plugin defines a set of tags so the user can tag his page in order for the plugin to know whether the page should be added to the robots.txt file.</p>]]>
    </param>
  </content>
</snap-tree>
<!-- vim: ts=2 sw=2 et syntax=xml
-->
