<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!--
  There are several sources to find top level domain names. These ones
  are quite complete and easy to work with:

  http://en.wikipedia.org/wiki/List_of_Internet_top-level_domains
  http://publicsuffix.org/

  For new TLDs (companies, cities, international, etc.)
  http://newgtlds.icann.org/en/program-status/delegated-strings

  TLD library - - TLD declarations in XML
  Copyright (C) 2011-2014  Made to Order Software Corp.

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
-->
<!DOCTYPE tld [
<!ELEMENT tld (area)+>
<!ELEMENT area (#PCDATA|forbid|exceptions)*>
<!ATTLIST area category (international|professionals|language|groups|region|technical|country|entrepreneurial) #REQUIRED
               country CDATA ""
               nic CDATA "">
<!ELEMENT forbid (#PCDATA)>
<!ATTLIST forbid reason (proposed|deprecated|unused|reserved|infrastructure) #REQUIRED>
<!ELEMENT exceptions (#PCDATA)>
<!ATTLIST exceptions apply-to CDATA #REQUIRED>
]>
<tld>
  <!-- international (for the whole world) -->
  <area category="international">
    .academy .agency .airforce .archi .associates

    .bar .bargains .best .bid .bike .biz .black .blackfriday .blue
    .boutique .build .buzz

    .cab .camera .camp .capital .cards .care .career .careers .cash .catering
    .center .ceo .cheap .christmas .cleaning .clinic .clothing .club
    .codes .coffee .college .com .community .company .computer
    .condos .construction .consulting .contractors .cooking .cool .coop
    .country .creditcard .cruises

    .dance .dating .democrat .diamonds .directory .discount
    .domains

    .edu .education .email .engineering .enterprises .equipment .estate
    .eu.int .events .exchange .expert .exposed

    .fail .farm .feedback .finance .financial .fish .fishing .fitness .flights
    .florist .foo .foundation .frogans .fund .furniture .futbol

    .gallery .gift .glass .gop .graphics .gratis .gripe .guitars .guru

    .haus .holdings .holiday .horse .house

    .immobilien .industries .info .ink .institute .insure .int .international
    .investments

    .jetzt .jobs

    .kaufen .kitchen .kim .koeln .kred

    .land .lease .lighting .limited .limo .link .luxury

    .maison .management .marketing .media .meet .menu .mobi
    .moda .moe .monash

    .name .net .ninja

    .org

    .partners .parts .photo .photography .photos .pics .pictures
    .pink .productions .properties .pub

    .post <!-- Also the .post is defined as "having a complex second level
            domain name rules", technically, it has no second level domain -->

    .qpon <!-- "coupon" -->

    .recipes .red .reisen .rentals .repair .report .republican .rest .reviews
    .rich .rocks .rodeo .ruhr

    .schule .services .sexy .shiksha .shoes .singles .social

    .solar .solutions .soy .supplies .supply .support .systems

    .tattoo .tax .technology .tel .tienda .tips .today .tools .town
    .toys .trade .training .travel

    .university .uno

    .vacations .ventures .viajes .vision .villas .vodka .vote .voting
    .voto .voyage

    .wang .watch .webcam .wed .wiki .works .wtc .wtf

    .xxx .xyz

    .zone

    .&#x0434;&#x0435;&#x0442;&#x0438; <!-- kids (Russian) -->
    .&#x043E;&#x043D;&#x043B;&#x0430;&#x0439;&#x043D; <!-- online (Russian) -->
    .&#x043E;&#x0440;&#x0433; <!-- organization (Russian) -->
    .&#x0441;&#x0430;&#x0439;&#x0442; <!-- site (Russian) -->
    .&#x0628;&#x0627;&#x0632;&#x0627;&#x0631; <!-- bazaar (Arabic) -->
    .&#x0634;&#x0628;&#x0643;&#x0629; <!-- web/network (Arabic) -->
    .&#x0938;&#x0902;&#x0917;&#x0920;&#x0928; <!-- organization (Hindi) -->
    .&#x307F;&#x3093;&#x306A; <!-- everyone (Japanese) -->
    .&#x4E16;&#x754C; <!-- world (Chinese) -->
    .&#x4E2D;&#x6587;&#x7F51; <!-- chinesenetwork (Chinese) -->
    .&#x516C;&#x53F8; <!-- company (Chinese) -->
    .&#x516C;&#x76CA; <!-- charity (Chinese) -->
    .&#x5546;&#x57CE; <!-- mail (Chinese) -->
    .&#x5728;&#x7EBF; <!-- online (Chinese) -->
    .&#x6211;&#x7231;&#x4F60; <!-- I love you (Chinese) -->
    .&#x653F;&#x52A1; <!-- government (Chinese) -->
    .&#x673A;&#x6784; <!-- agencies/institutions (Chinese) -->
    .&#x6E38;&#x620F; <!-- games (Chinese) -->
    .&#x79FB;&#x52A8; <!-- mobile (Chinese) -->
    .&#x7EC4;&#x7EC7;&#x673A;&#x6784; <!-- organization (Chinese) -->
    .&#x7F51;&#x5740; <!-- network address (Chinese) -->
    .&#x7F51;&#x7EDC; <!-- network (Chinese) -->
    .&#x96C6;&#x56E2; <!-- group (Chinese) -->

    <!-- yeah... .areo has gone crazy https://www.information.aero/ -->
    .aero .accident-investigation.aero .accident-prevention.aero
    .aerobatic.aero .aeroclub.aero .aerodrome.aero .agents.aero .aircraft.aero
    .airline.aero .airport.aero .air-surveillance.aero .airtraffic.aero
    .air-traffic-control.aero .ambulance.aero .amusement.aero .association.aero
    .author.aero .ballooning.aero .broker.aero .caa.aero .cargo.aero
    .catering.aero .certification.aero .championship.aero .charter.aero
    .civilaviation.aero .club.aero .conference.aero .consultant.aero
    .consulting.aero .control.aero .council.aero .crew.aero .design.aero
    .dgca.aero .educator.aero .emergency.aero .engine.aero .engineer.aero
    .entertainment.aero .equipment.aero .exchange.aero .express.aero
    .federation.aero .flight.aero .freight.aero .fuel.aero .gliding.aero
    .government.aero .groundhandling.aero .group.aero .hanggliding.aero
    .homebuilt.aero .insurance.aero .journal.aero .journalist.aero .leasing.aero
    .logistics.aero .magazine.aero .maintenance.aero .marketplace.aero
    .media.aero .microlight.aero .modelling.aero .navigation.aero
    .parachuting.aero .paragliding.aero .passenger-association.aero .pilot.aero
    .press.aero .production.aero .recreation.aero .repbody.aero .res.aero
    .research.aero .rotorcraft.aero .safety.aero .scientist.aero .services.aero
    .show.aero .skydiving.aero .software.aero .student.aero .taxi.aero
    .trader.aero .trading.aero .trainer.aero .union.aero .workinggroup.aero
    .works.aero

    <!-- yeah... this is the .museum total craziness! -->
    .museum .academy.museum .agriculture.museum .air.museum .airguard.museum
    .alabama.museum .alaska.museum .amber.museum .ambulance.museum
    .american.museum .americana.museum .americanantiques.museum
    .americanart.museum .amsterdam.museum .and.museum .annefrank.museum
    .anthro.museum .anthropology.museum .antiques.museum .aquarium.museum
    .arboretum.museum .archaeological.museum .archaeology.museum
    .architecture.museum .art.museum .artanddesign.museum .artcenter.museum
    .artdeco.museum .arteducation.museum .artgallery.museum .arts.museum
    .artsandcrafts.museum .asmatart.museum .assassination.museum .assisi.museum
    .association.museum .astronomy.museum .atlanta.museum .austin.museum
    .australia.museum .automotive.museum .aviation.museum .axis.museum
    .badajoz.museum .baghdad.museum .bahn.museum .bale.museum .baltimore.museum
    .barcelona.museum .baseball.museum .basel.museum .baths.museum
    .bauern.museum .beauxarts.museum .beeldengeluid.museum .bellevue.museum
    .bergbau.museum .berkeley.museum .berlin.museum .bern.museum .bible.museum
    .bilbao.museum .bill.museum .birdart.museum .birthplace.museum .bonn.museum
    .boston.museum .botanical.museum .botanicalgarden.museum
    .botanicgarden.museum .botany.museum .brandywinevalley.museum .brasil.museum
    .bristol.museum .british.museum .britishcolumbia.museum .broadcast.museum
    .brunel.museum .brussel.museum .brussels.museum .bruxelles.museum
    .building.museum .burghof.museum .bus.museum .bushey.museum
    .cadaques.museum .california.museum .cambridge.museum .can.museum
    .canada.museum .capebreton.museum .carrier.museum .cartoonart.museum
    .casadelamoneda.museum .castle.museum .castres.museum .celtic.museum
    .center.museum .chattanooga.museum .cheltenham.museum .chesapeakebay.museum
    .chicago.museum .children.museum .childrens.museum .childrensgarden.museum
    .chiropractic.museum .chocolate.museum .christiansburg.museum
    .cincinnati.museum .cinema.museum .circus.museum .civilisation.museum
    .civilization.museum .civilwar.museum .clinton.museum .clock.museum
    .coal.museum .coastaldefence.museum .cody.museum .coldwar.museum
    .collection.museum .colonialwilliamsburg.museum .coloradoplateau.museum
    .columbia.museum .columbus.museum .communication.museum
    .communications.museum .community.museum .computer.museum
    .computerhistory.museum .comunica&#x00E7;&#x00F5;es.museum
    .contemporary.museum .contemporaryart.museum .convent.museum
    .copenhagen.museum .corporation.museum
    .correios-e-telecomunica&#x00E7;&#x00F5;es.museum
    .corvette.museum .costume.museum .countryestate.museum .county.museum
    .crafts.museum .cranbrook.museum .creation.museum .cultural.museum
    .culturalcenter.museum .culture.museum .cyber.museum .cymru.museum
    .dali.museum .dallas.museum .database.museum .ddr.museum
    .decorativearts.museum .delaware.museum .delmenhorst.museum .denmark.museum
    .depot.museum .design.museum .detroit.museum .dinosaur.museum
    .discovery.museum .dolls.museum .donostia.museum .durham.museum
    .eastafrica.museum .eastcoast.museum .education.museum .educational.museum
    .egyptian.museum .eisenbahn.museum .elburg.museum .elvendrell.museum
    .embroidery.museum .encyclopedic.museum .england.museum .entomology.museum
    .environment.museum .environmentalconservation.museum .epilepsy.museum
    .essex.museum .estate.museum .ethnology.museum .exeter.museum
    .exhibition.museum .family.museum .farm.museum .farmequipment.museum
    .farmers.museum .farmstead.museum .field.museum .figueres.museum
    .filatelia.museum .film.museum .fineart.museum .finearts.museum
    .finland.museum .flanders.museum .florida.museum .force.museum
    .fortmissoula.museum .fortworth.museum .foundation.museum .francaise.museum
    .frankfurt.museum .franziskaner.museum .freemasonry.museum .freiburg.museum
    .fribourg.museum .frog.museum .fundacio.museum .furniture.museum
    .gallery.museum .garden.museum .gateway.museum .geelvinck.museum
    .gemological.museum .geology.museum .georgia.museum .giessen.museum
    .glas.museum .glass.museum .gorge.museum .grandrapids.museum .graz.museum
    .guernsey.museum .halloffame.museum .hamburg.museum .handson.museum
    .harvestcelebration.museum .hawaii.museum .health.museum
    .heimatunduhren.museum .hellas.museum .helsinki.museum
    .hembygdsforbund.museum .heritage.museum .histoire.museum .historical.museum
    .historicalsociety.museum .historichouses.museum .historisch.museum
    .historisches.museum .history.museum .historyofscience.museum
    .horology.museum .house.museum .humanities.museum .illustration.museum
    .imageandsound.museum .indian.museum .indiana.museum
    .indianapolis.museum .indianmarket.museum .intelligence.museum
    .interactive.museum .iraq.museum .iron.museum
    .isleofman.museum .jamison.museum .jefferson.museum
    .jerusalem.museum .jewelry.museum .jewish.museum
    .jewishart.museum .jfk.museum .journalism.museum
    .judaica.museum .judygarland.museum .juedisches.museum
    .juif.museum .karate.museum .karikatur.museum
    .kids.museum .koebenhavn.museum .koeln.museum
    .kunst.museum .kunstsammlung.museum .kunstunddesign.museum
    .labor.museum .labour.museum .lajolla.museum
    .lancashire.museum .landes.museum .lans.museum .l&#x00E4;ns.museum
    .larsson.museum .lewismiller.museum .lincoln.museum .linz.museum
    .living.museum .livinghistory.museum .localhistory.museum .london.museum
    .losangeles.museum .louvre.museum .loyalist.museum .lucerne.museum
    .luxembourg.museum .luzern.museum .mad.museum .madrid.museum
    .mallorca.museum .manchester.museum .mansion.museum .mansions.museum
    .manx.museum .marburg.museum .maritime.museum .maritimo.museum
    .maryland.museum .marylhurst.museum .media.museum .medical.museum
    .medizinhistorisches.museum .meeres.museum .memorial.museum
    .mesaverde.museum .michigan.museum .midatlantic.museum .military.museum
    .mill.museum .miners.museum .mining.museum .minnesota.museum
    .missile.museum .missoula.museum .modern.museum .moma.museum
    .money.museum .monmouth.museum .monticello.museum .montreal.museum
    .moscow.museum .motorcycle.museum .muenchen.museum .muenster.museum
    .mulhouse.museum .muncie.museum .museet.museum .museumcenter.museum
    .museumvereniging.museum .music.museum .national.museum
    .nationalfirearms.museum .nationalheritage.museum .nativeamerican.museum
    .naturalhistory.museum .naturalhistorymuseum.museum .naturalsciences.museum
    .nature.museum .naturhistorisches.museum .natuurwetenschappen.museum
    .naumburg.museum .naval.museum .nebraska.museum
    .neues.museum .newhampshire.museum .newjersey.museum
    .newmexico.museum .newport.museum .newspaper.museum
    .newyork.museum .niepce.museum .norfolk.museum
    .north.museum .nrw.museum .nuernberg.museum
    .nuremberg.museum .nyc.museum .nyny.museum
    .oceanographic.museum .oceanographique.museum .omaha.museum
    .online.museum .ontario.museum .openair.museum
    .oregon.museum .oregontrail.museum .otago.museum
    .oxford.museum .pacific.museum .paderborn.museum
    .palace.museum .paleo.museum .palmsprings.museum
    .panama.museum .paris.museum .pasadena.museum
    .pharmacy.museum .philadelphia.museum .philadelphiaarea.museum
    .philately.museum .phoenix.museum .photography.museum
    .pilots.museum .pittsburgh.museum .planetarium.museum
    .plantation.museum .plants.museum .plaza.museum
    .portal.museum .portland.museum .portlligat.museum
    .posts-and-telecommunications.museum .preservation.museum .presidio.museum
    .press.museum .project.museum .public.museum
    .pubol.museum .quebec.museum .railroad.museum
    .railway.museum .research.museum .resistance.museum .riodejaneiro.museum
    .rochester.museum .rockart.museum .roma.museum .russia.museum
    .saintlouis.museum .salem.museum .salvadordali.museum .salzburg.museum
    .sandiego.museum .sanfrancisco.museum .santabarbara.museum .santacruz.museum
    .santafe.museum .saskatchewan.museum .satx.museum .savannahga.museum
    .schlesisches.museum .schoenbrunn.museum .schokoladen.museum .school.museum
    .schweiz.museum .science.museum .scienceandhistory.museum
    .scienceandindustry.museum .sciencecenter.museum .sciencecenters.museum
    .science-fiction.museum .sciencehistory.museum .sciences.museum
    .sciencesnaturelles.museum .scotland.museum .seaport.museum
    .settlement.museum .settlers.museum .shell.museum .sherbrooke.museum
    .sibenik.museum .silk.museum .ski.museum .skole.museum .society.museum
    .sologne.museum .soundandvision.museum .southcarolina.museum
    .southwest.museum .space.museum .spy.museum .square.museum .stadt.museum
    .stalbans.museum .starnberg.museum .state.museum .stateofdelaware.museum
    .station.museum .steam.museum .steiermark.museum .stjohn.museum
    .stockholm.museum .stpetersburg.museum .stuttgart.museum .suisse.museum
    .surgeonshall.museum .surrey.museum .svizzera.museum .sweden.museum
    .sydney.museum .tank.museum .tcm.museum .technology.museum
    .telekommunikation.museum .television.museum .texas.museum .textile.museum
    .theater.museum .time.museum .timekeeping.museum .topology.museum
    .torino.museum .touch.museum .town.museum .transport.museum
    .tree.museum .trolley.museum .trust.museum .trustee.museum
    .uhren.museum .ulm.museum .undersea.museum .university.museum
    .usa.museum .usantiques.museum .usarts.museum .uscountryestate.museum
    .usculture.museum .usdecorativearts.museum .usgarden.museum
    .ushistory.museum .ushuaia.museum .uslivinghistory.museum .utah.museum
    .uvic.museum .valley.museum .vantaa.museum .versailles.museum
    .viking.museum .village.museum .virginia.museum .virtual.museum
    .virtuel.museum .vlaanderen.museum .volkenkunde.museum .wales.museum
    .wallonie.museum .war.museum .washingtondc.museum .watchandclock.museum
    .watch-and-clock.museum .western.museum .westfalen.museum .whaling.museum
    .wildlife.museum .williamsburg.museum .windmill.museum .workshop.museum
    .york.museum .yorkshire.museum .yosemite.museum .youth.museum
    .zoological.museum .zoology.museum
    .&#x05D9;&#x05E8;&#x05D5;&#x05E9;&#x05DC;&#x05D9;&#x05DD;.museum
    .&#x0438;&#x043A;&#x043E;&#x043C;.museum

    <forbid reason="deprecated">.nato</forbid>
    <forbid reason="proposed">.mail .med .shop .sport .web .wine</forbid>
  </area>

  <!-- specialized TLDs -->
  <area category="brand">
    .axa .citic .desi .dnp .mango .neustar .onl .ren .sohu
    .&#x4E2D;&#x4FE1; <!-- citic (Chinese) -->
    .&#xC0BC;&#xC131; <!-- samsung (Korean) -->
  </area>
  <area category="professionals">
    .actor .builders .dental .plumbing
    .pro .aaa.pro .aca.pro .acct.pro .avocat.pro .bar.pro .cpa.pro .eng.pro
    .jur.pro .law.pro .med.pro .recht.pro .surgery
  </area>
  <area category="language">
    .cat .eus .gal
    <forbid reason="proposed">.bzh .ker .lli .scot</forbid>
  </area>
  <area category="groups">
    <forbid reason="proposed">.kids .nai .eco .gay .fc</forbid>
  </area>
  <area category="region">
    .aq .asia .berlin .cologne .eu .kiwi .london .miami .moscow .nagoya
    .nyc .okinawa .paris .quebec .ryukyu .saarland .tokyo .vegas .wien .yokohama
    .&#x043C;&#x043E;&#x0441;&#x043A;&#x0432;&#x0430; <!-- moscow (Russian) -->
    <!-- the .cs and .yu were assigned to countries that are no more
         because of splits; as such it is difficult to place them in
         a specific country -->
    <forbid reason="unused">.cs .yu</forbid>
    <forbid reason="proposed">.geo .lat .africa .eng .sci</forbid>
  </area>
  <area category="technical">
    <!-- .local is used by Mac OS/X as in computername.local
         it is also used by mDNS -->
    <forbid reason="infrastructure">.arpa .e164.arpa .in-addr.arpa
    .ip6.arpa .iris.arpa .uri.arpa .urn.arpa .local</forbid>
  </area>

  <!-- countries, sorted by country name in English -->
  <area category="country" country="Afghanistan">
    .af .com.af .edu.af .gov.af .net.af .org.af
  </area>
  <area category="country" country="&#xC5;land Islands">
    .ax
  </area>
  <area category="country" country="Albania">
    .al .com.al .edu.al .gov.al .mil.al .net.al .org.al
  </area>
  <area category="country" country="Algeria">
    .dz .art.dz .asso.dz .com.dz .edu.dz .gov.dz .net.dz .org.dz .pol.dz
    .&#x0627;&#x0644;&#x062C;&#x0632;&#x0627;&#x0626;&#x0631;
  </area>
  <area category="country" country="American Samoa">
    .as .gov.as
  </area>
  <area category="country" country="Andorra">
    .ad .nom.ad
  </area>
  <area category="country" country="Angola">
    .ao .ed.ao .gv.ao .og.ao .co.ao .it.ao .pb.ao
  </area>
  <area category="country" country="Anguilla">
    .ai .com.ai .net.ai .off.ai .org.ai
  </area>
  <area category="country" country="Antigua &amp; Barbuda">
    .ag .co.ag .com.ag .net.ag .nom.ag .org.ag
  </area>
  <area category="country" country="Argentina">
    .com.ar .edu.ar .gob.ar .gov.ar .int.ar .mil.ar .net.ar .org.ar .tur.ar
    <forbid reason="unused">.ar</forbid>
    <exceptions apply-to=".ar">.congresodelalengua3.ar .educ.ar
    .gobiernoelectronico.ar .mecon.ar .nacion.ar .nic.ar .promocion.ar
    .retina.ar .uba.ar</exceptions>
  </area>
  <area category="country" country="Armenia">
    .am .com.am .net.am .org.am
  </area>
  <area category="country" country="Aruba">
    .aw .com.aw
  </area>
  <area category="country" country="Ascension Island">
    .ac .com.ac .edu.ac .net.ac .gov.ac .org.ac .mil.ac
  </area>
  <area category="country" country="Australia">
    .com.au .net.au .org.au .edu.au .gov.au .csiro.au .asn.au .id.au
    .wa.edu.au .wa.gov.au .vic.edu.au .vic.gov.au .qld.edu.au .qld.gov.au
    .sa.edu.au .sa.gov.au .tas.edu.au .tas.gov.au .nt.edu.au .nt.gov.au
    .act.edu.au .act.gov.au .schools.nsw.edu.au .eq.edu.au .act.au .nsw.au
    .nt.au .qld.au .sa.au .tas.au .vic.au .wa.au
    <forbid reason="unused">.au .nsw.edu.au</forbid>
    <forbid reason="deprecated">.archie.au .conf.au .gw.au .info.au .otc.au
    .oz.au .telememo.au</forbid>
  </area>
  <area category="country" country="Austria">
    .at .ac.at .biz.at .co.at .gv.at .info.at .or.at .priv.at
  </area>
  <area category="country" country="Azerbaijan">
    .az .com.az .net.az .int.az .gov.az .org.az .edu.az .info.az .pp.az .mil.az
    .name.az .pro.az .biz.az .co.az
  </area>
  <area category="country" country="Bahamas">
    .bs .com.bs .net.bs .org.bs .edu.bs .gov.bs .we.bs
  </area>
  <area category="country" country="Bahrain">
    .bh .com.bh .info.bh .cc.bh .edu.bh .biz.bh .net.bh .org.bh .gov.bh
  </area>
  <area category="country" country="Bangladesh">
    <!-- 2nd level not permitted -->
    <forbid reason="unused">.bd</forbid>
    .com.bd .edu.bd .ac.bd .net.bd .gov.bd .org.bd .mil.bd
    .&#x09AC;&#x09BE;&#x0982;&#x09B2;&#x09BE;
  </area>
  <area category="country" country="Barbados">
    .bb .co.bb .com.bb .net.bb .org.bb .gov.bb .edu.bb .info.bb .store.bb
    .tv.bb .biz.bb
  </area>
  <area category="country" country="Belarus">
    <!-- .ac.be is not official but we still require it here -->
    .by .com.by .gov.by .mil.by .of.by
  </area>
  <area category="country" country="Belgium">
    <!-- .ac.be is not official but we still require it here -->
    .be .ac.be
  </area>
  <area category="country" country="Belize">
    .bz .com.bz .edu.bz .gov.bz .net.bz .org.bz
  </area>
  <area category="country" country="Benin">
    <!-- the 2nd level are not all listed -->
    .bj .asso.bj .barreau.bj .com.bj .edu.bj .gouv.bj .gov.bj .mil.bj
  </area>
  <area category="country" country="Bermuda">
    .bm .com.bm .edu.bm .gov.bm .net.bm .org.bm
  </area>
  <area category="country" country="Bhutan">
    .bt .com.bt .edu.bt .gov.bt .net.bt .org.bt
  </area>
  <area category="country" country="Bolivia">
    .bo .com.bo .net.bo .org.bo .tv.bo .mil.bo .int.bo .gob.bo .gov.bo .edu.bo
  </area>
  <area category="country" country="Bonaire, Sint Eustatius and Saba">
    .bq
  </area>
  <area category="country" country="Bosnia and Herzegovina">
    .ba .web.ba .org.ba .net.ba .edu.ba .gov.ba .mil.ba .unsa.ba .untz.ba
    .unmo.ba .unbi.ba .unze.ba .co.ba .com.ba .rs.ba
  </area>
  <area category="country" country="Botswana">
    .bw .co.bw .org.bw
  </area>
  <area category="country" country="Bouvet Island">
    <forbid reason="unused">.bv</forbid>
  </area>
  <area category="country" country="Brazil">
    .br .adm.br .adv.br .agr.br .am.br .arq.br .art.br .ato.br .b.br .bio.br
    .blog.br .bmd.br .cim.br .cng.br .cnt.br .com.br .coop.br .ecn.br .eco.br
    .edu.br .emp.br .eng.br .esp.br .etc.br .eti.br .far.br .flog.br .fm.br
    .fnd.br .fot.br .fst.br .g12.br .ggf.br .gov.br .imb.br .ind.br .inf.br
    .jor.br .jus.br .leg.br .lel.br .mat.br .med.br .mil.br .mp.br .mus.br
    .net.br .nom.br .not.br .ntr.br .odo.br .org.br .ppg.br .pro.br .psc.br
    .psi.br .qsl.br .radio.br .rec.br .slg.br .srv.br .taxi.br .teo.br .tmp.br
    .trd.br .tur.br .tv.br .vet.br .vlog.br .wiki.br .zlg.br
    <!-- I'm not too sure what happened to .can.br,
         whether it ever really existed -->
    <forbid reason="deprecated">.can.br</forbid>
  </area>
  <area category="country" country="British Indian Ocean Territory">
    .io .com.io .net.io .org.io
  </area>
  <area category="country" country="British Virgin Islands">
    .vg
  </area>
  <area category="country" country="Brunei Darussalam">
    .com.bn .edu.bn .gov.bn .net.bn .org.bn
    <forbid reason="unused">.bn</forbid>
  </area>
  <area category="country" country="Bulgaria">
    .bg .a.bg .b.bg .c.bg .d.bg .e.bg .f.bg .g.bg .h.bg .i.bg .j.bg .k.bg .l.bg
    .m.bg .n.bg .o.bg .p.bg .q.bg .r.bg .s.bg .t.bg .u.bg .v.bg .w.bg .x.bg
    .y.bg .z.bg .0.bg .1.bg .2.bg .3.bg .4.bg .5.bg .6.bg .7.bg .8.bg .9.bg
    <forbid reason="proposed">.&#x0431;&#x0433;</forbid>
  </area>
  <area category="country" country="Burkina Faso">
    .bf .gov.bf
  </area>
  <area category="country" country="Burundi">
    .bi .co.bi .com.bi .edu.bi .gov.bi .info.bi .or.bi .org.bi
  </area>
  <area category="country" country="Cameroon">
    .cm .co.cm .com.cm .edu.cm .gov.cm .net.cm
  </area>
  <area category="country" country="Cape Verde">
    .cv .net.cv .gov.cv .org.cv .edu.cv .int.cv .publ.cv .com.cv .nome.cv 
  </area>
  <area category="country" country="Cambodia">
    <forbid reason="unused">.kh</forbid>
    .per.kh .com.kh .edu.kh .gov.kh .mil.kh .net.kh .org.kh
  </area>
  <area category="country" country="Canada">
    .ca .ab.ca .bc.ca .gc.ca .mb.ca .nb.ca .nl.ca .ns.ca .nt.ca .nu.ca .on.ca
    .pe.ca .qc.ca .sk.ca .yk.ca
    <forbid reason="deprecated">.nf.ca</forbid>
  </area>
  <area category="country" country="Cayman Islands">
    .ky .com.ky .org.ky .net.ky .edu.ky .gov.ky
    <forbid reason="unused">.cym</forbid>
  </area>
  <area category="country" country="Central African Republic">
    .cf
  </area>
  <area category="country" country="Chad">
    .td
  </area>
  <area category="country" country="Chile">
    .cl .co.cl .gov.cl .gob.cl .mil.cl
  </area>
  <area category="country" country="Christmas Island">
    .cx .gov.cx
  </area>
  <area category="country" country="Cocos Islands">
    <!-- all third level domain names are not official but we probably won't
         get them using Snap! Websites (not soon at least) and if we do, then
         we can fix this entry. Anyone else will have to use a sub-domain -->
    .cc .co.cc .cx.cc .cz.cc .uni.cc
  </area>
  <area category="country" country="Comoros">
    .km .com.km .coop.km .asso.km .nom.km .presse.km .tm.km .medecin.km
    .notaires.km .pharmaciens.km .veterinaire.km .edu.km .gouv.km .mil.km
    .org.km .gov.km .prd.km .ass.km
  </area>
  <area category="country" country="Cook Islands">
    .co.ck .org.ck .edu.ck .gov.ck .net.ck .gen.ck .biz.ck .info.ck
    <forbid reason="unused">.ck</forbid>
    <exceptions apply-to=".ck">.www.ck</exceptions>
  </area>
  <area category="country" country="Costa Rica">
    .cr .ac.cr .co.cr .ed.cr .fi.cr .go.cr .or.cr .sa.cr
  </area>
  <area category="country" country="C&#xF4;te d'Ivoire">
    .ci .ac.ci .a&#xE9;roport.ci  .asso.ci .com.ci .co.ci .edu.ci .ed.ci .go.ci
    .int.ci .net.ci .org.ci .or.ci .presse.ci .md.ci .gouv.ci
  </area>
  <area category="country" country="Croatia">
    .hr .com.hr .name.hr .from.hr .iz.hr
  </area>
  <area category="country" country="Cuba">
    .cu .com.cu .edu.cu .org.cu .net.cu .gov.cu .inf.cu
  </area>
  <area category="country" country="Cura&#xE7;ao">
    .cw .com.cw .edu.cw .net.cw .org.cw
  </area>
  <area category="country" country="Cyprus">
    .ac.cy .net.cy .gov.cy .org.cy .pro.cy .name.cy .ekloges.cy .tm.cy
    .ltd.cy .biz.cy .press.cy .parliament.cy .com.cy
    <!-- nearly all websites are required to use a 3rd level name; the .cy
         is used by some companies such as nic.cy -->
    <forbid reason="reserved">.cy</forbid>
  </area>
  <area category="country" country="Czech Repulic">
    .cz
  </area>
  <area category="country" country="Democratic People's Republic of Korea">
    .kp .com.kp .rep.kp .org.kp .edu.kp .gov.kp .tra.kp
  </area>
  <area category="country" country="Democratic Republic of the Congo">
    .cd .gov.cd
    <!-- .zr was for Zaire -->
    <forbid reason="deprecated">.zr</forbid>
  </area>
  <area category="country" country="Denmark">
    .dk
  </area>
  <area category="country" country="Djibouti">
    .dj
  </area>
  <area category="country" country="Dominica">
    .dm .com.dm .edu.dm .gov.dm .net.dm .org.dm
  </area>
  <area category="country" country="Dominican Republic">
    .do .art.do .com.do .edu.do .gob.do .gov.do .mil.do .net.do .org.do .sld.do
    .web.do
  </area>
  <area category="country" country="East Timor">
    .tl .gov.tl .tp
    <!-- .tp is being phased out, old East Timor -->
  </area>
  <area category="country" country="Ecuador">
    .ec .com.ec .info.ec .net.ec .fin.ec .med.ec .pro.ec .org.ec .edu.ec
    .gob.ec .gov.ec .mil.ec .k12.ec
  </area>
  <area category="country" country="Egypt">
    .eg .com.eg .edu.eg .eun.eg .gov.eg .mil.eg .name.eg .net.eg .org.eg .sci.eg
    .&#x0645;&#x0635;&#x0631;
  </area>
  <area category="country" country="El Salvador">
    .edu.sv .gob.sv .com.sv .org.sv .red.sv
    <forbid reason="unused">.sv</forbid>
  </area>
  <area category="country" country="Equatorial Guinea">
    .gq
  </area>
  <area category="country" country="Eritrea">
    .com.er .edu.er .gov.er .mil.er .net.er .org.er .ind.er
    <forbid reason="unused">.er</forbid>
  </area>
  <area category="country" country="Estonia">
    .ee .com.ee .pri.ee .fie.ee .med.ee .edu.ee .gov.ee .riik.ee .lib.ee
    .aip.ee .org.ee
  </area>
  <area category="country" country="Ethiopia">
    <!-- only 3rd level authorized -->
    <forbid reason="unused">.et</forbid>
    .com.et .gov.et .org.et .edu.et .net.et .biz.et .name.et .info.et
  </area>
  <area category="country" country="Falkland Islands">
    <forbid reason="unused">.fk</forbid>
    .co.fk .org.fk .gov.fk .ac.fk .nom.fk .net.fk
  </area>
  <area category="country" country="Faroe Islands">
    .fo
  </area>
  <area category="country" country="Federated States of Micronesia">
    .fm
  </area>