<?xml version="1.0" standalone="yes"?>
<!--
Snap Websites Server == mailinglist database setup
Copyright (C) 2013  Made to Order Software Corp.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
-->
<!DOCTYPE snap-tree [
<!ELEMENT snap-tree (content)*>
<!ELEMENT content (param|link)*>
<!ATTLIST content path CDATA #REQUIRED>
<!ELEMENT param (#PCDATA)>
<!ATTLIST param name CDATA #REQUIRED
                overwrite (yes|no) "no"
                force-namespace (yes|no) "yes">
<!ELEMENT link (#PCDATA)>
<!ATTLIST link name CDATA #REQUIRED
               to CDATA #REQUIRED
               mode CDATA "1:1">
]>
<snap-tree>
  <content path="/admin/settings/mailinglist">
    <param name="content::title">Mailing List Administration</param>
    <param name="content::body">
      <![CDATA[<p>Administration of your mailing lists.</p>]]>
    </param>
  </content>
  <content path="/types/mailinglist/status">
    <param name="content::title">Mailing List Status</param>
    <param name="content::body">
      <![CDATA[<p>Different statuses used by mailing lists. These statuses are managed internally only.</p>]]>
    </param>
    <link name="permissions::administration" to="permissions::administration" mode="1:*">/types/permissions/rights/administration</link>
  </content>
</snap-tree>
<!-- vim: ts=2 sw=2 et syntax=xml
-->
